spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/board-api-msa/config.git
          default-label: main

server:
  port: 8888

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"